routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('/questions', 'QuestionsController');
Route::resource('/profiles','ProfileController');
Route::put('/profiles','ProfileController@update');
Route::resource('/answers','AnswersController');

app/Answers.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Answers extends Model
{
    //
    protected $guarded=[];

}

app/Http/Controllers/AnswersController.php
<?php

namespace App\Http\Controllers;

use App\Answers;
use Illuminate\Http\Request;
use DB;

class AnswersController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

   public function index()
   {
     $answers = Answers::all();

     return view('answers.index', compact('answers'));
   }

   /**
    * Show the form for creating a new resource.
    *
    * @return \Illuminate\Http\Response
    */
   public function create()
   {
       return view('answers.create');
   }

   /**
    * Store a newly created resource in storage.
    *
    * @param  \Illuminate\Http\Request  $request
    * @return \Illuminate\Http\Response
    */
   public function store(Request $request)
   {
       //validate
       $this->validate($request, [

         'body'=>'required'
       ]);

       //store
       Answers::create([
         'body' => $request['body'],
         'author' => auth()->user()->name,
         'user_id' => auth()->user()->id
       ]);

       //redirect
       return redirect('/answers');
   }

   /**
    * Display the specified resource.
    *
    * @param  \App\Answers  $questions
    * @return \Illuminate\Http\Response
    */
   public function show($id)
   {
       $answer = Answers::find($id);

       return view('answers.show', compact('answer'));
   }

   /**
    * Show the form for editing the specified resource.
    *
    * @param  \App\Answers  $questions
    * @return \Illuminate\Http\Response
    */
   public function edit($id)
   {
       $answer = Answers::find($id);

       return view('answers.edit', compact('answer'));
   }

   /**
    * Update the specified resource in storage.
    *
    * @param  \Illuminate\Http\Request  $request
    * @param  \App\Answers  $questions
    * @return \Illuminate\Http\Response
    */
   public function update(Request $request, $id)
   {
       Answers::where('id', $id)->update([
         'body' => $request['body']
       ]);

       return redirect('/answers');
   }

   /**
    * Remove the specified resource from storage.
    *
    * @param  \App\Answers  $questions
    * @return \Illuminate\Http\Response
    */
   public function destroy($id)
   {
       Answers::destroy($id);

       return redirect('/answers');
   }
}

resources/views/answers/create.blade.php
@extends('layouts.app')

@section('heading', 'Buat Jawaban')

@section('content')
  <form class="" action="{{ route('answers.store') }}" method="post">
    @csrf
    <div class="form-group">
      <label for="exampleTextarea">Isi Jawaban</label>
      <textarea class="form-control" name="body" id="exampleTextarea" placeholder="Tulis Pertanyaan" rows="3">{{ old('body') }}</textarea>
    </div>
    <div class="row mt-4">
      <div class="col-sm-12 text-right">
        <a href="{{ url()->previous() }}" class="btn btn-default">Kembali</a>
        <button type="submit" class="btn btn-primary">Submit</button>
      </div>
    </div>
  </form>
@endsection

resources/views/answers/edit.blade.php
@extends('layouts.app')

@section('heading', 'Edit Jawaban')

@section('content')
  <form class="" action="{{ route('answers.update', ['answer' => $answer->id]) }}" method="post">
    @csrf
    @method('PUT')
    <div class="form-group">
      <label for="exampleTextarea">Isi Jawaban</label>
      <textarea class="form-control" name="body" id="exampleTextarea" placeholder="Tulis Jawaban" rows="3">{{ $answer->body }}</textarea>
    </div>
    <div class="row mt-4">
      <div class="col-sm-12 text-right">
        <a href="{{ url()->previous() }}" class="btn btn-default">Kembali</a>
        <button type="submit" class="btn btn-primary">Edit</button>
      </div>
    </div>
  </form>
@endsection

resources/views/answers/index.blade.php
@extends('layouts.app')

@section('heading', 'Jawaban')

@section('button')
  <div class="col-sm-2 my-auto">
    <a class="btn btn-primary" href="{{ route('answers.create') }}">Menjawab</a>
  </div>
@endsection

@section('content')
  <div class="list-group">
    @forelse ($answers ?? '' as $key => $answer)
      <a href="{{ route('answers.show', ['answer' => $answer->id]) }}" class="list-group-item list-group-item-action flex-column align-items-start">
        <div class="d-flex w-100 justify-content-between">
          <small class="text-muted">{{ $answer->created_at }}</small>
        </div>
        <p class="mb-1">{{ $answer->body }}</p>
        <small class="text-muted">{{ $answer->author_id }}</small>
      </a>
    @empty
      <h5>No Data</h5>
    @endforelse
  </div>
@endsection

resources/views/answers/show.blade.php
@extends('layouts.app')

@section('heading', 'Tampilkan Jawaban')

@section('content')
  <p style="font-size: 18px">{{ $answer->body }}</p>
  <p style="font-size: 15px">by {{$answer->author}} at {{ $answer->created_at }}</p>
  <div class="row mt-4">
    <div class="col-sm-12 text-right">
      <a href="{{ url()->previous() }}" class="btn btn-default">Kembali</a>
      <a href="{{ route('answers.edit', ['answer' => $answer->id]) }}" class="btn btn-primary">Edit</a>
    </div>
    <div class="mt-4 col-sm-12 text-right">
      <form action="{{ route('answers.destroy', ['answer' => $answer->id]) }}" method="post">
        @csrf
        @method('DELETE')
        <input type="submit" name="delete" value="Delete" class="btn btn-danger">
      </form>
    </div>
  </div>
@endsection