routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('/questions', 'QuestionsController');
Route::resource('/profiles','ProfileController');
Route::put('/profiles','ProfileController@update');
Route::resource('/answers','AnswersController');

app/Questions.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Questions extends Model
{
    protected $guarded=[];

    public function answers() {
        return $this->hasMany('App\Answers');
    }
}

app/Http/Controllers/QuestionsController.php
<?php

namespace App\Http\Controllers;

use App\Questions;
use Illuminate\Http\Request;
use DB;

class QuestionsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
     public function __construct()
     {
         $this->middleware('auth');
     }

    public function index()
    {
      $questions = Questions::all();

      return view('questions.index', compact('questions'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('questions.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //validate
        $this->validate($request, [
          'title'=>'required',
          'body'=>'required'
        ]);

        //store
        Questions::create([
          'title' => $request['title'],
          'body' => $request['body'],
          'author' => auth()->user()->name,
          'user_id' => auth()->user()->id
        ]);

        //redirect
        return redirect('/questions');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Questions  $questions
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $question = Questions::find($id);

        return view('questions.show', compact('question'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Questions  $questions
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $question = Questions::find($id);

        return view('questions.edit', compact('question'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Questions  $questions
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        Questions::where('id', $id)->update([
          'title' => $request['title'],
          'body' => $request['body']
        ]);

        return redirect('/questions');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Questions  $questions
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Questions::destroy($id);

        return redirect('/questions');
    }
}

resources/views/questions/create.blade.php
@extends('layouts.app')

@section('heading', 'Buat Pertanyaan')

@section('content')
  <form class="" action="{{ route('questions.store') }}" method="post">
    @csrf
    <div class="form-group">
      <label class="col-form-label col-form-label-lg" for="inputLarge">Judul</label>
      <input class="form-control form-control-lg" name="title" type="text" placeholder="Tulis Judul" value="{{ old('title') }}" id="inputLarge">
    </div>
    <div class="form-group">
      <label for="exampleTextarea">Isi Pertanyaan</label>
      <textarea class="form-control" name="body" id="exampleTextarea" placeholder="Tulis Pertanyaan" rows="3">{{ old('body') }}</textarea>
    </div>
    <div class="row mt-4">
      <div class="col-sm-12 text-right">
        <a href="{{ url()->previous() }}" class="btn btn-default">Kembali</a>
        <button type="submit" class="btn btn-primary">Submit</button>
      </div>
    </div>
  </form>
@endsection

resources/views/questions/edit.blade.php
@extends('layouts.app')

@section('heading', 'Edit Pertanyaan')

@section('content')
  <form class="" action="{{ route('questions.update', ['question' => $question->id]) }}" method="post">
    @csrf
    @method('PUT')
    <div class="form-group">
      <label class="col-form-label col-form-label-lg" for="inputLarge">Judul</label>
      <input class="form-control form-control-lg" name="title" type="text" placeholder="Tulis Judul" value="{{ $question->title }}" id="inputLarge">
    </div>
    <div class="form-group">
      <label for="exampleTextarea">Isi Pertanyaan</label>
      <textarea class="form-control" name="body" id="exampleTextarea" placeholder="Tulis Pertanyaan" rows="3">{{ $question->body }}</textarea>
    </div>
    <div class="row mt-4">
      <div class="col-sm-12 text-right">
        <a href="{{ url()->previous() }}" class="btn btn-default">Kembali</a>
        <button type="submit" class="btn btn-primary">Edit</button>
      </div>
    </div>
  </form>
@endsection

resources/views/questions/index.blade.php
@extends('layouts.app')

@section('heading', 'Pertanyaan')

@section('button')
  <div class="col-sm-2 my-auto">
    <a class="btn btn-primary" href="{{ route('questions.create') }}">Bertanya</a>
  </div>
@endsection

@section('content')
  <div class="list-group">
    @forelse ($questions ?? '' as $key => $question)
      <a href="{{ route('questions.show', ['question' => $question->id]) }}" class="list-group-item list-group-item-action flex-column align-items-start">
        <div class="d-flex w-100 justify-content-between">
          <h5 class="mb-1">{{ $question->title }}</h5>
          <small class="text-muted">{{ $question->created_at }}</small>
        </div>
        <p class="mb-1">{{ $question->body }}</p>
        <small class="text-muted">{{ $question->author }}</small>
      </a>
    @empty
      <h5>No Data</h5>
    @endforelse
  </div>
@endsection

resources/views/questions/show.blade.php
@extends('layouts.app')

@section('heading', 'Tampilkan Pertanyaan')

@section('content')
  <h3>{{ $question->title }}</h3>
  <p style="font-size: 18px">{{ $question->body }}</p>
  <p style="font-size: 15px">by {{$question->author}} at {{ $question->created_at }}</p>
  <a href="{{ route('answers.create') }}" class="btn btn-default">Jawab</a>
  <div class="row mt-4">
    <div class="col-sm-12 text-right">
      <a href="{{ url()->previous() }}" class="btn btn-default">Kembali</a>
      <a href="{{ route('questions.edit', ['question' => $question->id]) }}" class="btn btn-primary">Edit</a>
    </div>
    <div class="mt-4 col-sm-12 text-right">
      <form action="{{ route('questions.destroy', ['question' => $question->id]) }}" method="post">
        @csrf
        @method('DELETE')
        <input type="submit" name="delete" value="Delete" class="btn btn-danger">
      </form>
    </div>
  </div>
@endsection